package org.proyectosalida.Constructores;

public enum Caracteristica {

    //COMIDA
    PINTXOS,  COMBINADOS,  COCINA_INTERNACIONAL, COCINA_LOCAL, RACIONES, BRUNCH, CENAS, ALMUERZOS, COCINA_MEDITERRANEA,
   DESAYUNOS, CARTA_VARIADA, COCINA_GOURMET, COCINA_CASERA,
    COMIDA_VEGANA, COMIDA_VEGETARIANA, MENUS_DIARIOS, ENSALADAS, TAPAS, TARTAS_CASERAS,


    //BEBIDA
    CERVEZAS, CERVEZA_ROPA_INTERNACIONAL,CERVEZA_ROPA_ARTESANAL, CERVEZA_ARTESANAL_LOCAL, CERVEZA_ARTESANAL_IMPORTADA,
    CERVEZA_IMPORTADA, COCTELES_PREMIUM, COCTELES, VINOS, CERVEZA_ARTESANAL, CERVEZA_ROPA, COPAS, COCTELERIA_CREATIVE,


    //ACTIVIDADES
    MUSICA, FUTBOL, BILLAR, DARDOS, DEPORTES, KARAOKE, DJ, MUSICA_INDIE, MUSICA_DIRECTO, PUB_QUIZ, CONCIERTOS_JAZZ,
    CUMPLEAÑOS, HAPPY_HOUR, MUSICA_ELECTRONICA, JUEGOS_TRIVIA,  FIESTAS_TEMATICAS, JUEGOS_MESA, BAILE, CONCIERTOS,
    SHISHA, EVENTOS_EN_VIVO, TARDEO, AFTERWORK, NOCHE_VIEJA, ESPECTACULOS, ACTUACIONES_DIRECTO, PROYECCIONES, TALLERES,
    CENA_ESPECTACULO, BAILE_LATINO, KARAOKE_NOCHES, CATERING_EVENTOS, JAZZ, POKER, CENA_ESPECTACULO_FLAMENCO,


    //INSTALACIONES
    TERRAZA, ZONA_PRIVADA, ACCESIBILIDAD, WIFI, RESTAURANTE, VISTAS,
    PISCINA, MASCOTAS_PERMITIDAS,  TERRAZA_CHILLOUT,  TERRAZA_AMPLIA,


    //SERVICIOS
    SERVICIO_COMIDA_DOMICILIO, SERVICIO_COMIDA, SERVICIO_TERRAZA,  DESCUENTOS,


}

