package org.proyectosalida.Constructores;

public enum Caracteristica {
    PINTXOS, TERRAZA, CERVEZAS, MUSICA, FUTBOL, BILLAR, DARDOS, COMBINADOS,
    ZONA_PRIVADA, ACCESIBILIDAD, VINTAGE, PETFRIENDLY, DEPORTES, WIFI,
    KARAOKE, DJ, RESTAURANTE, COCINA_INTERNACIONAL, COCINA_LOCAL, HAPPY_HOUR,
    SHISHA, COCTELES, VINOS, CERVEZA_ARTESANAL, BAILE, CONCIERTOS, PISCINA,
    VISTAS_PANORAMICAS, SALA_VIP, EVENTOS_EN_VIVO, TARDEO, AFTERWORK, DESAYUNOS,
    BRUNCH, CENAS, ALMUERZOS, FIESTAS_TEMATICAS, JUEGOS_MESA, CERVEZA_ROPA,
    SERVICIO_COMIDA, SERVICIO_TERRAZA, DESCUENTOS, MASCOTAS_PERMITIDAS,
    ESPECTACULOS, ACTUACIONES_DIRECTO, PROYECCIONES, TERRAZA_CHILLOUT, TALLERES,
    CARTA_VARIADA, COCINA_GOURMET, CENA_ESPECTACULO, BAILE_LATINO,
    KARAOKE_NOCHES, COCINA_CASERA, TERRAZA_AMPLIA, COPAS, RESTAURANTE_VISTAS,
     CATERING_EVENTOS,  JAZZ,
    COMIDA_VEGANA, COMIDA_VEGETARIANA, MENUS_DIARIOS, ENSALADAS, TAPAS,
    PUB_QUIZ, CONCIERTOS_JAZZ, CUMPLEAÑOS, COCTELERIA_CREATIVE, POKER,
    CENA_ESPECTACULO_FLAMENCO, TARTAS_CASERAS, CERVEZA_ARTESANAL_LOCAL,
    CERVEZA_IMPORTADA, COCINA_INTERNACIONAL_LOCAL, COCTELES_PREMIUM,
    CERVEZA_ROPA_INTERNACIONAL, JUEGOS_TRIVIA, CERVEZA_ROPA_ARTESANAL,
    COCINA_MEDITERRANEA, MUSICA_DIRECTO, COCINA_CREATIVE, SERVICIO_COMIDA_DOMICILIO,
    RACIONES, MUSICA_INDIE, REUNIONES, MUSICA_ELECTRONICA, CERVEZA_ARTESANAL_IMPORTADA
}

